config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ideas#index'
  # to create a like, we need a idea id in the url therefore nest it resources

  resources :ideas do
    resources :likes, only: [:create, :destroy], shallow: true

    resources :members, only: [:create, :destroy], shallow: true

    resources :comments, only: [:create, :destroy], shallow: true
  end
  

  resources :users


  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


end

app/models/idea.rb
class Idea < ApplicationRecord

  belongs_to :user
  has_many :likes, dependent: :destroy

  has_many :liked_by_users, through: :likes, source: :user

  has_many :members, dependent: :destroy

  has_many :memberships, through: :members, source: :user
  has_many :comments, dependent: :destroy
  # @idea.membership should give us a list of users
  # in idea and want to list the user that are members

  # has_many :user
  # ideas liked by users

  validates :title, presence: true
  validates :body, presence: true

  def like_for(user)
    likes.find_by(user: user)
  end


  # check this method on the idea object, checking the method of one idea has to be the method of idea
  # each idea has a table of likes look for the user passed and look for the list, calls likes find the user
  def membership_for(user)
    members.find_by(user: user)
    # inside idea = table of members, members find look for idea members see if any user_id you passed in. find it means it joined and will pass member entry back
    # user = user_id
  end




end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action  :find_idea, {only: [:show, :edit, :update, :destroy]}

  before_action :authenticate_access, only: [:edit, :update, :destroy]


  def index
    @ideas = Idea.all.order(created_at: :desc)
  end

  def new
    @idea = Idea.new
  end

  def create
    # just before we save we want to add the current user id to the idea

    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to idea_path(@idea), notice: "New Idea Created"
    else
      flash[:alert] = "noooo idea"
      render :new
    end
  end

  def show
    # the comment is suppose to be displayed on an idea, therefore this is where the form is getting called
    # ArgumentError in Ideas#show
    # Showing /Users/Jyang/Desktop/projects/awesome_quiz3/app/views/comments/_commentform.html.erb where line #2 raised:
    #
    # First argument in form cannot contain nil or be empty
    # Extracted source (around line #2):

    # <h2>Make a comment</h2>
    # <%= form_for [@idea, @comment] do |r|%>
    # <%#=@idea, @comment is from nested routes and @idea @comment is defined in the show page   def find_idea
    #     @idea = Idea.find params[:id]
    #   end is defined in the idea controller show action %>
    #  <div>
    @idea = Idea.find params[:id]
    # find idea
    @comment = Comment.new
    # make a new comment


  end

  def edit



  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea)
    else
      flash[:alert] = "fix errors"
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to root_path

  end

  private

  def idea_params
    params.require(:idea).permit([:title, :body])
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def authenticate_access
    if cannot?(:edit_delete, @idea)
      # if current_user can edit delete this idea
      redirect_to root_path, alert: "unauthorized access"
    end

  end


end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_ideaform.html.erb
<%= @idea.errors.full_messages.join(", ") %>

<%= form_for @idea do |f| %>
 <div>
   <%= f.label :title %>
   <%= f.text_field :title %>
 </div>
 <div>
   <%= f.label :body %>
   <%= f.text_area :body %>
 </div>

 <%= f.submit("Add") %>
<% end %>

app/views/ideas/edit.html.erb
<h3>Edit Idea</h3>

<%= render "ideaform" %>

app/views/ideas/index.html.erb
<h1>List of all Ideas</h1>

<div>
  <% @ideas.each do |x| %>
  <div>
    <h2><%= link_to x.title, idea_path(x) %></h2>
    <p><%= x.body %></p>
    <% if can?(:like, x) %>
    <% like = x.like_for(current_user) %>
    <%#=checks ideas likes and see if current_user is in there and if it is then they can unlike it  %>
    <% if like != nil%>
    <%= link_to "Unlike", like_path(like), method: :delete %>
    <% else %>
    <%= link_to "Like", idea_likes_path(x), method: :post %>

    <% end %>
    <% end %>

    <% if can?(:join, x) %>
    <% member = x.membership_for(current_user) %>
    <% if member != nil %>
    <%= link_to "UnJoin", member_path(member), method: :delete %>
    <% else %>
    <%= link_to "Join", idea_members_path(x), method: :post  %>
    <% end %>
    <% end %>
    (<%= pluralize(x.likes.count, "like") %>)

    <hr>
  </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<h1>Make a New Idea</h1>

<h4>New</h4>



<%= render "ideaform" %>

app/views/ideas/show.html.erb
<h3>Show one idea</h3>
<%#= I D E A controller show action!!!! need to define variables  %>

<div>
Title : <%= @idea.title %> <br>
Body: <%= @idea.body %><br>

<% if user_signed_in? %>
<div>
  <%= render "comments/commentform" %>

  <%#=this form is getting rendered from the show.html.erb  %>
</div>
<hr>
<%#= do i want the hr to show up on each like if so have it inside a loop  %>
<% end %>

<br>


<div>

<h4>Comments</h4>
  <% @comments = @idea.comments %>
  <%#=@idea.comments will generate a list of comment can call this method because of the model association belongs to and has many  %>
  <% @comments.each do |x| %>
  <p>
    Posted By:<%= x.user.name %><br>
    Comment:<%= x.body %>
    <% if can?(:delete_comment, x)%><br>
      <button> <%= link_to "Delete", comment_path(x), method: :delete %></button>
    <% end %>
  </p>


  <% end %>
</div>
<hr>


<h4>Members</h4>
<ul>
  <%@idea.memberships.each do |user|%>
  <li><%= user.name %></li>
  <% end %>


</ul>

<% if can?(:edit_delete, @idea) %>
<%= link_to "Edit", edit_idea_path(@idea) %>
<%= link_to "Delete", idea_path(@idea),
                      method: :delete,
                      data: {confirm: "Are you sure?"} %>
created by: <%= @idea.user.name %>
<% end %>

<br>

(<%= pluralize(@idea.likes.count, "like") %>)

</div>


<hr>